#
# Makefile for the Linux kernel device drivers.
#
obj-$(CONFIG_SENSORS_PROXM)	+= proxm_class/
obj-$(CONFIG_SENSORS_ADUX1020)	+= adux-1020/
obj-$(CONFIG_SENSORS_CM32180)	+= cm32180/
obj-$(CONFIG_SENSORS_CM36283)	+= cm36283/
obj-$(CONFIG_SENSORS_CM3628)	+= cm3628/
obj-$(CONFIG_SENSORS_AL3010)	+= al3010/
obj-$(CONFIG_SENSORS_AL3320)	+= al3320/
obj-$(CONFIG_SENSORS_AP3212C)	+= ap3212c/


